### ISSUE TITLE
fix visual/ux bug: multiline input field covers chat section

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#13]
![image](https://user-images.githubusercontent.com/3581741/56125609-fa85bf80-5f81-11e9-9daa-4f5f4fd2c28c.png)

(it covers the last message)

**Comment by akariv** [comment]
This is according to the design, no?

**Comment by noamoss** [comment]
@akariv the input area should have fixed height, so the user can see the relevant question he/she are answering.

**Comment by akariv** [comment]
![Screen Shot 2019-04-15 at 15 42 47](https://user-images.githubusercontent.com/265333/56133516-43933f00-5f95-11e9-82aa-34cb0cd6d9dc.png)

**Comment by noamoss** [comment]
@akariv following our talk: 
![image](https://user-images.githubusercontent.com/3581741/56158236-35abe100-5fca-11e9-8e03-332e06f2d56b.png)

**Comment by noamoss** [comment]
checked and approved.
