### ISSUE TITLE
enable sending different reports with the same email address

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#14]
pilot users reported they cannot deliver reports using the same email as contact methods:
![image](https://user-images.githubusercontent.com/3581741/56226514-0e155100-607c-11e9-99f3-bca62db8f8b3.png)

(the screenshot was taken by user)

Two possible solutions:

1. If we move out of HubSpot, just to make sure the contact details fields are not restricted as unique.
2. If we decide to stay within HubSpot, we will need to create a new dummy field for user email (and ignore the standard field).

**Comment by akariv** [comment]
Fixed by moving out of HubSpot
