### ISSUE TITLE
add user input validators

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#2]
1. email address
2. phone number (to be applied over the whatsapp input as well): ddd-dd-ddddddd / dd-ddddddd / ddd-ddddddd.
3. date
4. time

![image](https://user-images.githubusercontent.com/3581741/54121693-d0c9fd80-4403-11e9-8ecc-0967ef3bf178.png)

**Comment by akariv** [comment]
Just add a function to test validity and integrate it into the script.

**Comment by noamoss** [comment]
@akariv please take over, as currently I can not dedicate time now writing these scripts. 
AFAIK currently we need:
1. phone number (to include just digits and dashes) 
2. email addresses

**Comment by noamoss** [comment]
@akariv added 'date' and 'time' validators to the description.

**Comment by noamoss** [comment]
@akariv the way it is implemented the editor (a nontechnical dude) is supposed to be familiar with Regex. It makes more sense to relate to validations as types (like in the description). doesn't it?

* date
* phone numbers
* time
* email address

**Comment by akariv** [comment]
This is exactly the kind of thing that the UI would abstract away.

Either way it's super easy to find 'good-enough' regexps in the internet (https://regexr.com/3c53v, https://emailregex.com/), and it gives the user the possibility to customize based on business logic (e.g. 'never accept hotmail accounts!' or 'only accept mobile numbers and not fixed numbers' etc.)
