### ISSUE TITLE
unexpected user input step

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#20]
![image](https://user-images.githubusercontent.com/3581741/60345778-69d85080-99c2-11e9-8ff9-8c4b2f635f0a.png)

**Comment by akariv** [comment]
Doesn't reproduce - and the script snippet you screenshotted is not relevant (what happens when isWorkingTime returns 'false' in your case? Where is it routed?

**Comment by noamoss** [comment]
closing issue, as I could not reproduce as well. fixing the script as you offered.

**Comment by noamoss** [comment]
@akariv 

>(what happens when isWorkingTime returns 'false' in your case? Where is it routed? 

it is routed to the right place, a branch named "בדיקת שעות עבודה: מענה מחוץ לשעות עבודה"

**Comment by noamoss** [comment]
The reopening issue, as it happens out of working hours:

It was rooted correctly via a script, but just to verify, I tried a more explicit way:

![image](https://user-images.githubusercontent.com/3581741/60760786-0a261900-a044-11e9-975b-e6e9bfd47653.png)

![image](https://user-images.githubusercontent.com/3581741/60760802-448fb600-a044-11e9-8366-6ca534cbacc6.png)

after typing in anything, the script continues to run normally.

**Comment by akariv** [comment]
Exercise to the reader - what happens on Saturday?

<img width="338" alt="Screen Shot 2019-07-07 at 0 00 33" src="https://user-images.githubusercontent.com/265333/60761087-5e33fc00-a04a-11e9-9fd9-e713d44393a0.png">

**Comment by noamoss** [comment]
hmm... my bad. thanks.
