### ISSUE TITLE
add auto scrolloing when new message/question appears

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#21]
after user types in an answer, a new respond/question is being displayed, but the new message is hidden beneath the window border:

![image](https://user-images.githubusercontent.com/3581741/60346209-5bd6ff80-99c3-11e9-9755-7f1b36b6e521.png)

we need an autoscrolling mechanism.

When the user scrolls down, this is what is happening:

![image](https://user-images.githubusercontent.com/3581741/60346492-ec154480-99c3-11e9-9338-e669c9fc6966.png)

**Comment by akariv** [comment]
Looks like you're not using the latest code version

**Comment by noamoss** [comment]
@akariv rechecked, local is updated. [browser details](whatismybrowser.com/w/T7R6AYP)

**Comment by noamoss** [comment]
@akariv problem still occurs on live with the same browser.

**Comment by akariv** [comment]
It wasn't deployed on live, now it is.

**Comment by noamoss** [comment]
checked and approved.
