### ISSUE TITLE
translate and display user UI in a chosen language

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#28]
This issue assumes a single script for user + agent (#26) with a translation to a non-Hebrew language (#27). 

Now we need to enable the user:

1. choose the desired language
2. go through the intake
3. save the language and integrate the follow-up conversation (agent side) with the selected language.

**Comment by akariv** [comment]
closing now as everything is ready (e.g. admin.equality.org.il/ar is alive and functional).
Once translation is done, we can test and also add the UI controls to select the language.
