### ISSUE TITLE
select questions are waiting for keyboard input

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#41]
this report is relevant for both user+agent:

![תמונה](https://user-images.githubusercontent.com/3581741/70798014-828cc500-1dae-11ea-95d4-76a835003086.png)

It might be related to the new script editor integration, therefore putting @oferb for cc.

**Comment by noamoss** [comment]
checked on live and approved. Opened a follow up report, see https://github.com/hasadna/reportit-user/issues/43

**Comment by noamoss** [comment]
reopenning, as this issue still exists on the agent side:
![image](https://user-images.githubusercontent.com/3581741/70832606-2fdaf980-1dfe-11ea-853c-9f345ddb616d.png)

**Comment by akariv** [comment]
This is part of the NGO selection loop, not part of the script.
When re-implementing this out side of the function it will not happen again.
If calling waitForInput inside a function, make sure to pass 'false' as a
parameter there.

**Comment by noamoss** [comment]
@akariv so this issue can be solved when the loop/recursive issue is solved (https://github.com/hasadna/reportit-agent/issues/53)
