### ISSUE TITLE
handle communication/delivery errors

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-user#7]
related to #2:

In addition to the user input validation, we should add two mechanisms to increase and ensure the flow:

* [ ] User: prevent the scenario from freezing (see screenshot below)- the script should move on. Let's inform the user that the last answer was not sent, and continue to the next question.
* [ ] Mokdan: send a notification to the sysadmin/mokdan when a submission fails. The notification should include the submitted data + the request + respond.

![image](https://user-images.githubusercontent.com/3581741/54164313-d9065500-4464-11e9-92a0-3272a6bce986.png)

**Comment by noamoss** [comment]
Another real-world example: user tried to upload a big file. Server returned 413 error but the user got no indication:

![image](https://user-images.githubusercontent.com/3581741/56228163-cc86a500-607f-11e9-983f-d26f17fb1ff6.png).

We should consider creating a response message object to notify the user what happened and how to handle + "other" item for nondefined error scenarios.

**Comment by akariv** [comment]
- Saving records is now happening in the background.
- Error handling is now happening with hasadna/reporit-agent#5
